### ISSUE TITLE
Signoff ZFS into UEK kernel and OL

### ISSUE THREAD

**Issue by mailinglists35** [oracle/zfssa-csi-driver#16]
Come'on Oracle, get over it. You can do it. You can still sell the appliance and sell the support for it. Allow the kernel modules and cli tools, you can keep the GUI for sale with the appliance, orgs that buys that kind of stuff want support anyways so your sales will not be affected. It's time to let go. Please do it. Let Solaris go die its death, cherry pick ZFS and whatelse from it and that's it. I'm pretty sure you are in secret running it on Linux already internally.

**Comment by pmonday** [comment]
Alas, the CSI driver contains no ZFSSA code. Only example code of using the APIs. I will close this and pass it on. Have you considered checking out the [Oracle ZFS Storage - High Availability](https://cloudmarketplace.oracle.com/marketplace/en_US/listing/122033460) image? This is a great way to change the model for usage if the hardware appliance does not fit your needs.

Cheers, thank you for the feedback.

**Comment by mailinglists35** [comment]
Thank you for passing the feedback somewhere inside! I could not find some other Oracle github repo to send the suggestion to.

The software appliance mentioned is too heavy footprint and unlike OpenZFS is not free.
